### ISSUE TITLE
"Play Runescape (Existing User)" only redirects to the downloads page if you have a forum account

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted-Website#14]
It should just direct to it anyways, no point requiring the user to register on forums to get DL link

**Comment by Dark98** [comment]
its working the way the original 06 website worked :p

**Comment by dginovker** [comment]
True, but I want to direct people to it in the advertisement posts and I don't want to kill them with over-registration. Up to you, I'll close this issue if not.

**Comment by Dark98** [comment]
i'd rather stick with the original rs06 mechanics, keeps the authentic feel
