### ISSUE TITLE
Server Player Save Integration

### ISSUE THREAD

**Issue by Dark98** [dginovker/2006rebotted-Website#9]

**Comment by dginovker** [comment]
We decided we're not gonna do that, since it would require 3 registrations to play the game. Close?

**Comment by Dark98** [comment]
Two registrations* your choice :p

**Comment by dginovker** [comment]
> Two registrations* your choice :p

I mean, Parabot + 2006rebotted.tk + 2006rebotted, even if the lattermost is an automatic registration. I think it's fine how it is for now, maybe we can revisit it one day :)

**Comment by Dark98** [comment]
You wouldn't "register" for the game,it would authenticate your username & password from the site db
